// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBegXwL4L7rCf2_HitFh1Fv6d3qwIPJglo',
    appId: '1:334013633258:web:9f450ccb510ff522b27d93',
    messagingSenderId: '334013633258',
    projectId: 'postagefee-65da3',
    authDomain: 'postagefee-65da3.firebaseapp.com',
    storageBucket: 'postagefee-65da3.appspot.com',
    measurementId: 'G-MRJCB63H8X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuFyZjuwwZC93bY4rr1H7Y2QrAMmQ5Me0',
    appId: '1:334013633258:android:1e73e9293ca97bf8b27d93',
    messagingSenderId: '334013633258',
    projectId: 'postagefee-65da3',
    storageBucket: 'postagefee-65da3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI6Y1aciqdS5ZB448-CutgWBCr7JJTshw',
    appId: '1:334013633258:ios:9f47b3f18229a34bb27d93',
    messagingSenderId: '334013633258',
    projectId: 'postagefee-65da3',
    storageBucket: 'postagefee-65da3.appspot.com',
    iosClientId: '334013633258-5nknhvc3hgqlatcdj5tn7erh3chkpor0.apps.googleusercontent.com',
    iosBundleId: 'com.example.postagecheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI6Y1aciqdS5ZB448-CutgWBCr7JJTshw',
    appId: '1:334013633258:ios:9f47b3f18229a34bb27d93',
    messagingSenderId: '334013633258',
    projectId: 'postagefee-65da3',
    storageBucket: 'postagefee-65da3.appspot.com',
    iosClientId: '334013633258-5nknhvc3hgqlatcdj5tn7erh3chkpor0.apps.googleusercontent.com',
    iosBundleId: 'com.example.postagecheck',
  );
}
